@startuml
!include sequence-style.puml
title Create Worker Test Sequence Diagram

actor "Worker" as W
participant "UI" as UI
participant "WorkerVerifyController" as C
participant "WorkerVerifyService" as S
participant "WorkerServiceService" as WS
participant "QuestionCategoryService" as QC
participant "WorkerVerificationTestService" as TS
participant "WorkerVerificationService" as VS
participant "QuestionService" as Q
database "DB" as DB

activate W
W -> UI : 1 Click "Thêm nghiệp vụ"
activate UI

UI -> C : 1.1 POST /createWorkerTest(request)
activate C
C -> S : 1.1.1 Gọi createWorkerTest(request)
activate S

S -> WS : 1.1.1.1 checkWorkerServiceExists(request.getServiceId())
activate WS
WS --> S : 1.1.1.2 Kết quả: true/false
deactivate WS

alt Worker đã có nghiệp vụ
    S -> S : 1.1.1.3a Ném lỗi WORKER_SERVICE_EXISTS
else Chưa có
    S -> QC : 1.1.1.3b getCategoryEntityByServiceId(request.getServiceId())
    activate QC
    QC --> S : 1.1.1.4 Trả về QuestionCategory
    deactivate QC

    S -> TS : 1.1.1.5 saveWorkerVerificationTest(...)
    activate TS
    TS -> DB : 1.1.1.5.1 INSERT WorkerVerificationTest
    DB --> TS : 1.1.1.5.2 OK
    TS --> S : 1.1.1.6 Trả về WorkerVerificationTest
    deactivate TS

    S -> VS : 1.1.1.7 saveWorkerVerification(...)
    activate VS
    VS -> DB : 1.1.1.7.1 INSERT WorkerVerification
    DB --> VS : 1.1.1.7.2 OK
    VS --> S : 1.1.1.8 Trả về WorkerVerification
    deactivate VS

    S -> Q : 1.1.1.9 findRandomQuestions(questionCategory.getId())
    activate Q
    Q --> S : 1.1.1.10 Trả về List<QuestionResponseDTO>
    deactivate Q
end

S --> C : 1.1.2 Trả về CreateTestResponseDTO(testId, questions)
deactivate S
C --> UI : 1.1.3 Giao diện danh sách câu hỏi
deactivate C


@enduml
