@startuml
<style>
    sequenceDiagram {
       FontSize 45
       ActorFontSize 45
       ParticipantFontSize 45
       TitleFontSize 45

       ParticipantPadding 25          ' Tăng khoảng giữa các participant
       ParticipantMargin 45           ' Tăng độ rộng tổng thể

       actor {
            BackgroundColor white
            LineThickness 1.0
       }
       participant {
            BackgroundColor white
            RoundCorner 0
       }
       database {
            BackgroundColor white
       }
       groupHeader {
            BackgroundColor white
       }
       referenceHeader {
            BackgroundColor white
       }
       reference {
            BackgroundColor white
       }
    }
</style>

scale max 2000 width

hide footbox
@enduml
