@startuml
<style>
    sequenceDiagram {
       actor {
            BackgroundColor white
            LineThickness 1.0
        }
        participant {
            BackgroundColor white
            RoundCorner 0
        }
        database {
            BackgroundColor white
        }
        groupHeader {
            BackgroundColor white
        }
        referenceHeader {
            BackgroundColor white
        }
        reference {
            BackgroundColor white
        }
    }
</style>
hide footbox
@enduml